name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]
  workflow_dispatch:

jobs:
  build_test:

    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --name autotests-chrome-runner-container --shm-size=2g
        ports:
          - 4445:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test

      - name: Copy History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history